# reusable workflow triggered by other actions
name: CI

on:
  workflow_call:
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true

jobs:
  lib-check:
    name: Check libraries
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_quality-checks.yaml@main
    secrets: inherit
    with:
        charm-path: "."

  lint:
    name: Lint Check
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install python3-pip tox

    - name: Lint code
      run: tox -e lint

  unit:
    name: Unit Test
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install python3-pip tox

    - name: Run unit tests
      run: tox -e unit

  integration:
    name: Integration Test (build and deploy)
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        tox-environments:
          - charm-integration
          - seldon-servers-integration
    steps:
    # Ideally we'd use self-hosted runners, but this effort is still not stable.
    # This action will remove unused software (dotnet, haskell, android libs, codeql,
    # and docker images) from the GH runner, which will liberate around 60 GB of storage
    # distributed in 40GB for root and around 20 for a mnt point.
    - name: Maximise GH runner space
      uses: easimon/maximize-build-space@v8
      with:
        root-reserve-mb: 40960
        remove-dotnet: 'true'
        remove-haskell: 'true'
        remove-android: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Check out repo
      uses: actions/checkout@v2

    - name: Setup operator environment
      uses: charmed-kubernetes/actions-operator@main
      with:
        provider: microk8s
        channel: 1.25-strict/stable
        microk8s-addons: "dns hostpath-storage rbac metallb:10.64.140.43-10.64.140.49"
        juju-channel: 3.1/stable
        charmcraft-channel: latest/candidate

    - name: Run integration tests
      run: tox -ve ${{ matrix.tox-environments }} -- --model testing

    # On failure, capture debugging resources
    - name: Get all
      run: kubectl get all -A
      if: failure()

    - name: Get juju status
      run: juju status
      if: failure()

    - name: Get workload logs
      run: kubectl logs --tail 100 -ntesting -lapp.kubernetes.io/name=seldon-controller-manager
      if: failure()

    - name: Get operator logs
      run: kubectl logs --tail 100 -ntesting -loperator.juju.is/name=seldon-controller-manager
      if: failure()
