name: On Pull Request

# On pull_request, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests

on:
  pull_request:

jobs:

  tests:
    name: Run Tests
    uses: ./.github/workflows/integrate.yaml
    secrets: inherit

  # publish runs in parallel with tests, as we always publish in this situation
  publish-charm:
    name: Publish Charm
    runs-on: ubuntu:20.04
    steps:
    - name: publish
      uses: ./.github/workflows/publish.yaml

    - name: debug
      uses: canonical/kubeflow-ci/actions/dump-charm-debug-artifacts@main
      # always() if you want this to run on every run, regardless of failure.
      # more details: https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
      if: always()


